router id 10.0.0.6;
protocol kernel { ipv4 { export all; import all; }; }
protocol device { scan time 10; }
protocol static {
    ipv4;
    route 10.4.3.0/30 blackhole;
}
protocol bgp sp1 { local 10.1.3.2 as 65006; neighbor 10.1.3.1 as 65001; ipv4 { import all; export all; }; }
protocol bgp sp2 { local 10.2.3.2 as 65006; neighbor 10.2.3.1 as 65001; ipv4 { import all; export all; }; }
protocol bgp sp3 { local 10.3.3.2 as 65006; neighbor 10.3.3.1 as 65001; ipv4 { import all; export all; }; }
