#!/usr/bin/env python3
"""
configure_bgp.py
Configures BGP on all spine/leaf/router devices using BIRD2.
Uses eBGP between all devices just like real hyperscale data centers.
Each leaf has its own AS number (AS per rack design).
Spines share AS 65001.
Router1 is AS 65000 simulating an edge/border router.
"""
import os
import yaml
import subprocess
import time

PREFIX = "clab-enterprise-spine-leaf"
HOST_VARS_DIR = os.path.expanduser("~/network-automation/host_vars")

# BGP design — AS numbers and peers for each device
BGP_DESIGN = {
    "router1": {
        "asn": 65000,
        "router_id": "10.0.0.254",
        "peers": [
            {"name": "SP1", "asn": 65001, "ip": "10.0.1.2"},
            {"name": "SP2", "asn": 65001, "ip": "10.0.2.2"},
            {"name": "SP3", "asn": 65001, "ip": "10.0.3.2"},
        ]
    },
    "SP1": {
        "asn": 65001,
        "router_id": "10.0.0.1",
        "peers": [
            {"name": "router1", "asn": 65000, "ip": "10.0.1.1"},
            {"name": "SP4",     "asn": 65004, "ip": "10.1.1.2"},
            {"name": "SP5",     "asn": 65005, "ip": "10.1.2.2"},
            {"name": "SP6",     "asn": 65006, "ip": "10.1.3.2"},
            {"name": "SP7",     "asn": 65007, "ip": "10.1.4.2"},
        ]
    },
    "SP2": {
        "asn": 65001,
        "router_id": "10.0.0.2",
        "peers": [
            {"name": "router1", "asn": 65000, "ip": "10.0.2.1"},
            {"name": "SP4",     "asn": 65004, "ip": "10.2.1.2"},
            {"name": "SP5",     "asn": 65005, "ip": "10.2.2.2"},
            {"name": "SP6",     "asn": 65006, "ip": "10.2.3.2"},
            {"name": "SP7",     "asn": 65007, "ip": "10.2.4.2"},
        ]
    },
    "SP3": {
        "asn": 65001,
        "router_id": "10.0.0.3",
        "peers": [
            {"name": "router1", "asn": 65000, "ip": "10.0.3.1"},
            {"name": "SP4",     "asn": 65004, "ip": "10.3.1.2"},
            {"name": "SP5",     "asn": 65005, "ip": "10.3.2.2"},
            {"name": "SP6",     "asn": 65006, "ip": "10.3.3.2"},
            {"name": "SP7",     "asn": 65007, "ip": "10.3.4.2"},
        ]
    },
    "SP4": {
        "asn": 65004,
        "router_id": "10.0.0.4",
        "peers": [
            {"name": "SP1", "asn": 65001, "ip": "10.1.1.1"},
            {"name": "SP2", "asn": 65001, "ip": "10.2.1.1"},
            {"name": "SP3", "asn": 65001, "ip": "10.3.1.1"},
        ]
    },
    "SP5": {
        "asn": 65005,
        "router_id": "10.0.0.5",
        "peers": [
            {"name": "SP1", "asn": 65001, "ip": "10.1.2.1"},
            {"name": "SP2", "asn": 65001, "ip": "10.2.2.1"},
            {"name": "SP3", "asn": 65001, "ip": "10.3.2.1"},
        ]
    },
    "SP6": {
        "asn": 65006,
        "router_id": "10.0.0.6",
        "peers": [
            {"name": "SP1", "asn": 65001, "ip": "10.1.3.1"},
            {"name": "SP2", "asn": 65001, "ip": "10.2.3.1"},
            {"name": "SP3", "asn": 65001, "ip": "10.3.3.1"},
        ]
    },
    "SP7": {
        "asn": 65007,
        "router_id": "10.0.0.7",
        "peers": [
            {"name": "SP1", "asn": 65001, "ip": "10.1.4.1"},
            {"name": "SP2", "asn": 65001, "ip": "10.2.4.1"},
            {"name": "SP3", "asn": 65001, "ip": "10.3.4.1"},
        ]
    },
}

def generate_bgp_config(device_name, device_data):
    """
    Generate BIRD2 BGP configuration for a device.
    Each peer gets its own BGP protocol block.
    We export all routes so every device knows about every subnet.
    """
    asn = device_data["asn"]
    router_id = device_data["router_id"]

    # Build one BGP protocol block per peer
    peer_blocks = ""
    for peer in device_data["peers"]:
        peer_blocks += f"""
protocol bgp {peer['name'].lower()} {{
    # eBGP session to {peer['name']} in AS{peer['asn']}
    local as {asn};
    neighbor {peer['ip']} as {peer['asn']};
    ipv4 {{
        import all;   # accept all routes from this peer
        export all;   # advertise all our routes to this peer
    }};
}}
"""

    config = f"""# BIRD2 BGP Configuration for {device_name}
# AS{asn} — generated by configure_bgp.py
# eBGP design: each device peers with its directly connected neighbors
# This mirrors real hyperscale data center BGP design (AS per rack)

router id {router_id};

# Sync routes between BIRD and the Linux kernel routing table
protocol kernel {{
    ipv4 {{
        export all;
        import all;
    }};
}}

protocol device {{
    scan time 10;
}}

# Static routes — advertise our directly connected subnets into BGP
protocol static {{
    ipv4;
    include "/etc/bird_statics.conf";
}}

{peer_blocks}
"""
    return config

def generate_static_routes(device_name, interfaces):
    """
    Generate static route entries for all directly connected subnets.
    These get advertised into BGP so other devices know about our subnets.
    """
    routes = "# Static routes for directly connected subnets\n"
    for iface in interfaces:
        if iface["name"] == "eth0":
            continue
        routes += f"route {iface['ip']}/{iface['prefix']} blackhole;\n"
    return routes

def push_bgp_config(device_name, config, static_routes):
    """
    Push BGP config and static routes into the container.
    Restart BIRD to apply the new configuration.
    """
    container = f"{PREFIX}-{device_name}"

    # Write main BGP config
    cmd = f"cat > /etc/bird.conf << 'BIRDEOF'\n{config}\nBIRDEOF"
    subprocess.run(
        ["sudo", "docker", "exec", container, "sh", "-c", cmd],
        capture_output=True
    )

    # Write static routes file
    cmd2 = f"cat > /etc/bird_statics.conf << 'STATICEOF'\n{static_routes}\nSTATICEOF"
    subprocess.run(
        ["sudo", "docker", "exec", container, "sh", "-c", cmd2],
        capture_output=True
    )

    # Restart BIRD with new config
    subprocess.run(
        ["sudo", "docker", "exec", container, "sh", "-c",
         "pkill bird || true; sleep 1; bird -c /etc/bird.conf"],
        capture_output=True
    )
    print(f"  BGP configured on {device_name} (AS{BGP_DESIGN[device_name]['asn']})")

def verify_bgp(device_name):
    """
    Check BGP session status.
    Established means two devices are exchanging routes.
    Active means BGP is trying to connect but not yet established.
    """
    container = f"{PREFIX}-{device_name}"
    result = subprocess.run(
        ["sudo", "docker", "exec", container, "sh", "-c",
         "birdc show protocols | grep -A1 BGP || birdc show protocols"],
        capture_output=True, text=True
    )
    print(f"\n--- {device_name} BGP sessions ---")
    print(result.stdout if result.stdout else "No BGP sessions yet")

# Main execution
print("Configuring BGP on all devices...\n")

for device_name, device_data in BGP_DESIGN.items():
    print(f"Configuring {device_name} (AS{device_data['asn']})...")

    # Load interfaces from host_vars
    filepath = os.path.join(HOST_VARS_DIR, f"{device_name}.yml")
    with open(filepath, "r") as f:
        host_data = yaml.safe_load(f)

    interfaces = host_data.get("interfaces", [])
    static_routes = generate_static_routes(device_name, interfaces)
    config = generate_bgp_config(device_name, device_data)
    push_bgp_config(device_name, config, static_routes)

print("\nWaiting 30 seconds for BGP sessions to establish...")
time.sleep(30)

print("\nVerifying BGP sessions...")
for device in ["SP1", "SP2", "SP3"]:
    verify_bgp(device)

print("\nVerifying routing table on SP4...")
container = f"{PREFIX}-SP4"
result = subprocess.run(
    ["sudo", "docker", "exec", container, "sh", "-c", "ip route show"],
    capture_output=True, text=True
)
print(result.stdout)

print("\nDone — BGP configured on all devices!")
