interfaces:
- ip: 10.0.1.2
  name: eth1
  prefix: 30
- ip: 10.1.1.1
  name: eth2
  prefix: 30
- ip: 10.1.2.1
  name: eth3
  prefix: 30
- ip: 10.1.3.1
  name: eth4
  prefix: 30
- ip: 10.1.4.1
  name: eth5
  prefix: 30
